services:
  todos:
    image: todos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
      - 443:8081
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - AuthorizedUser=${AuthorizedUser}
      - AuthorizedUserPassword=${AuthorizedUserPassword}
      - TODO_API_FIRESTOREDB_PROJECT=${TODO_API_FIRESTOREDB_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS_BASE64=${GOOGLE_APPLICATION_CREDENTIALS_BASE64}
